# Generated by Django 3.1.1 on 2020-09-15 10:18

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'earwear'), ('L', 'laptop'), ('C', 'clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True, verbose_name='slug'),
        ),
    ]
