# Generated by Django 3.1.1 on 2020-09-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200911_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('R', 'red'), ('G', 'green')], max_length=1),
        ),
    ]
