# Generated by Django 3.1.1 on 2020-09-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200911_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='S', upload_to='home/products/images'),
            preserve_default=False,
        ),
    ]
