# Generated by Django 3.1.1 on 2020-09-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200914_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='same_billing_address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='save_address',
        ),
    ]
